[build]
  functions = "functions"
  command = "netlify-lambda install && mkdir ./public"
[template.environment]
  FAUNA_SECRET_KEY = "FaunaDB secret key here"
  TELEGRAM_BOT_TOKEN = "1073817484:AAHdH8vekqG2hDY-8kPWADY2CCv1j_w9P1I
"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200